name: CI

on:
  push:
    branches:
      - master  # или ваша рабочая ветка
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: nouchka/sqlite3
        ports:
          - 8080:8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python Equipment_accounting_system/manage.py migrate  # Правильный путь к manage.py

      - name: Run tests
        run: python Equipment_accounting_system/manage.py test  # Правильный путь к manage.py
